import random,shutil
#   ---Cooking a dict---
def Cook():
    text = ['txt', 'md', 'rtf', 'log', 'csv', 'tex', 'xml', 'json', 'yaml']
    image = ['ai', 'bmp', 'eps', 'gif', 'heif', 'ico', 'jpg', 'png', 'svg', 'tiff', 'webp']
    audio = ['aac', 'aiff', 'alac', 'au', 'flac', 'm4a', 'mid', 'mp3', 'ogg', 'opus', 'wav', 'wma']
    video = ['3gp', 'avi', 'flv', 'hevc', 'mkv', 'mov', 'mp4', 'mpeg', 'mts', 'ogv', 'rmvb', 'webm', 'wmv']
    web = ['html', 'htm', 'xhtml', 'shtml', 'phtml', 'css', 'less', 'sass', 'scss', 'js', 'jsx', 'ts', 'tsx', 'php', 'asp', 'aspx', 'cgi', 'pl', 'xml', 'json', 'rss', 'atom', 'webmanifest', 'svg', 'ico', 'webp', 'ejs', 'njk', 'handlebars', 'mustache', 'wasm']
    archive = ['zip', 'tar', 'gz', 'bz2', 'xz', '7z', 'rar', 'ace', 'arj', 'cab', 'lz', 'lzh', 'z', 'uue', 'hqx', 'pax', 'cpio', 'tar.gz', 'tar.bz2', 'tar.xz']
    program = ['c', 'cpp', 'h', 'java', 'cs', 'py', 'rb', 'js', 'ts', 'php', 'swift', 'go', 'rs', 'kt', 'pl', 'lua', 'sh', 'bat', 'ps1', 'sql', 'vbs', 'r', 'd', 'm']

    fileExt = {t:"text" for t in text}
    fileExt.update({i:"image" for i in image})
    fileExt.update({a:"audio" for a in audio})
    fileExt.update({v:"video" for v in video})
    fileExt.update({w:"web" for w in web})
    fileExt.update({a:"archive" for a in archive})
    fileExt.update({p:"program" for p in program})
#Cook()
#   ---Made a dict---

fileExt = {'txt': 'text',
    'md': 'text',
    'rtf': 'text',
    'log': 'text',
    'csv': 'text',
    'tex': 'text',
    'xml': 'web',
    'json': 'web',
    'yaml': 'text',
    'ai': 'image',
    'bmp': 'image',
    'eps': 'image',
    'gif': 'image',
    'heif': 'image',
    'ico': 'web',
    'jpg': 'image',
    'png': 'image',
    'svg': 'web',
    'tiff': 'image',
    'webp': 'web',
    'aac': 'audio',
    'aiff': 'audio',
    'alac': 'audio',
    'au': 'audio',
    'flac': 'audio',
    'm4a': 'audio',
    'mid': 'audio',
    'mp3': 'audio',
    'ogg': 'audio',
    'opus': 'audio',
    'wav': 'audio',
    'wma': 'audio',
    '3gp': 'video',
    'avi': 'video',
    'flv': 'video',
    'hevc': 'video',
    'mkv': 'video',
    'mov': 'video',
    'mp4': 'video',
    'mpeg': 'video',
    'mts': 'video',
    'ogv': 'video',
    'rmvb': 'video',
    'webm': 'video',
    'wmv': 'video',
    'html': 'web',
    'htm': 'web',
    'xhtml': 'web',
    'shtml': 'web',
    'phtml': 'web',
    'css': 'web',
    'less': 'web',
    'sass': 'web',
    'scss': 'web',
    'js': 'program',
    'jsx': 'web',
    'ts': 'program',
    'tsx': 'web',
    'php': 'program',
    'asp': 'web',
    'aspx': 'web',
    'cgi': 'web',
    'pl': 'program',
    'rss': 'web',
    'atom': 'web',
    'webmanifest': 'web',
    'ejs': 'web',
    'njk': 'web',
    'handlebars': 'web',
    'mustache': 'web',
    'wasm': 'web',
    'zip': 'archive',
    'tar': 'archive',
    'gz': 'archive',
    'bz2': 'archive',
    'xz': 'archive',
    '7z': 'archive',
    'rar': 'archive',
    'ace': 'archive',
    'arj': 'archive',
    'cab': 'archive',
    'lz': 'archive',
    'lzh': 'archive',
    'z': 'archive',
    'uue': 'archive',
    'hqx': 'archive',
    'pax': 'archive',
    'cpio': 'archive',
    'tar.gz': 'archive',
    'tar.bz2': 'archive',
    'tar.xz': 'archive',
    'c': 'program',
    'cpp': 'program',
    'h': 'program',
    'java': 'program',
    'cs': 'program',
    'py': 'program',
    'rb': 'program',
    'swift': 'program',
    'go': 'program',
    'rs': 'program',
    'kt': 'program',
    'lua': 'program',
    'sh': 'program',
    'bat': 'program',
    'ps1': 'program',
    'sql': 'program',
    'vbs': 'program',
    'r': 'program',
    'd': 'program',
    'm': 'program'
    }
